### PR TITLE
.refactor & fix : improve efficiency,avoid repetition and fixed a bug.

### PR DESCRIPTION
**Pull request by Andy-AO**
simplify 'Set the appropriate foreground text colour.'
Eliminate redundant switches.

### CODE REVIEW

**Comment by Andy-AO** [comment]
Shorten the code from 57 lines to 38 lines, improve efficiency and avoid repetition.

**Comment by Andy-AO** [comment]
The most important thing is to fix the display bug on [PowerShell/vscode-powershell](https://github.com/PowerShell/vscode-powershell)(DeBug Mode). The previous method used in the PowerShell integrated console has no way to NoNewLine, leads to typesetting failure.

I forgot to add this to the message.

**Comment by KubaP** [comment]
It seems that these changes have been merged into pull request #2 . Can this one therefore be closed now?

**Comment by Andy-AO** [comment]
> It seems that these changes have been merged into pull request #2 . Can this one therefore be closed now?

Yes, I'm not familiar with GitHub. Some operations may be forgotten or wrong.

**Comment by KubaP** [comment]
Cool, no worries mate.

**Pull request closed without merging**
